# Generated by Django 5.1.4 on 2024-12-27 07:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_profile_followings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="followings",
            field=models.ManyToManyField(
                blank=True,
                related_name="follower_profiles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
