# Generated by Django 5.1.4 on 2024-12-24 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0004_article_like_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="price",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
