# Generated by Django 5.1.4 on 2024-12-24 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0005_article_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="price",
            field=models.IntegerField(),
        ),
    ]
